"""empty message

Revision ID: 461f01f0c75c
Revises: 66834b2983a7
Create Date: 2020-05-31 15:17:38.361290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461f01f0c75c'
down_revision = '66834b2983a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
