"""empty message

Revision ID: 70b4ee8965ac
Revises: 461f01f0c75c
Create Date: 2020-06-01 23:48:14.488835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b4ee8965ac'
down_revision = '461f01f0c75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('added', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'added')
    op.drop_column('Artist', 'added')
    # ### end Alembic commands ###
